models/Article.php
<?php
namespace app\models;

use yii\db\ActiveRecord;

class Article extends ActiveRecord
{

    public static function tableName()
    {
        return '{{%article}}';
    }

    public function rules()
    {
        return [
            [['name', 'user_id'], 'required'],
            [['name'], 'string'],
            [['text'], 'safe'],
            [['user_id'], 'number', 'min' => 1],
            [['user_id'], 'integer'],
            [['tag_article_id'], 'number', 'min' => 1],
	        [['tag_article_id'], 'integer']
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'Код',
            'name' => 'Заголовок',
            'text' => 'Текст',
            'user_id' => 'Пользователь',
            'tag_article_id' => 'Теги',
        ];
    }

    //////////////////////////////////////////////////////////////

    // relations
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

	public function getTags()
	{
		return $this->hasMany(TagArticle::className(), ['article_id' => 'id']);
	}

	public function getTagArticle()
	{
		return $this->hasMany(TagArticle::className(), ['article_id' => 'id']);
	}

	///////////////////////////////////////////////////// TestPoint

	public function getTagList()
	{
		$tagList = [];

		foreach($this->tags as $tagArticle)
		{
			$tagList[] = $tagArticle->tag->id;
		}

		return $tagList;
	}




}

views/admin/article/create.php
<?php
	$this->title = 'Создание';
	$this->params['breadcrumbs'] = [
        [
	        'label' => 'Статьи',
	        'url' => ['index']
        ],
		[
			'label' => $this->title,
		]
	];
?>

    <h1><?=$this->title; ?></h1>

    <?=$this->render('form', [
        'model' => $model,
        'tagList' => $tagList,
    ]); ?>

views/admin/article/form.php
<?php
	use yii\widgets\ActiveForm;
	use yii\helpers\Html;
	use \dosamigos\ckeditor\CKEditor;
	use kartik\select2\Select2;

?>
<?php $form = ActiveForm::begin([
	'id' => 'login-form',
	'options' => ['class' => 'form-horizontal'],
	'fieldConfig' => [
		'template' => '<div class="col-lg-12">{label}</div>
                       <div class="col-lg-3">{input}</div>
                       <div class="col-lg-9">{error}</div>',
		'labelOptions' => ['class' => 'control-label'],
	],
]); ?>

	<?=Html::hiddenInput(\Yii::$app->getRequest()->csrfParam, \Yii::$app->getRequest()->getCsrfToken(), []); ?>

	<?=$form->field($model, 'user_id')->hiddenInput(['value' => Yii::$app->user->id]); ?>
	<?=$form->field($model, 'name')->label(); ?>

	<?=Select2::widget([
		'name' => 'tag_id',
		'data' => $tagList,
		'value' => !$model->isNewRecord ? $selectList : null,
		'options' => [
			'placeholder' => 'Выбирите теги',
			'multiple' => true
		],
	]);?>

	<?=$form->field($model, 'text')->widget(CKEditor::className(), [
		'options' => ['rows' => 6],
		'preset' => 'advance'
	]) ?>

	<?=Html::submitButton($model->isNewRecord ? 'Создать' : 'Сохранить', ['class' => 'btn btn-success']); ?>

<?php ActiveForm::end() ?>

views/admin/article/index.php
<?php
    use \yii\grid\GridView;
    use \yii\helpers\Html;
    use \yii\widgets\Pjax;
    use \app\models\User;
    use \app\models\UserSearch;

	$this->title = 'Статьи';
    $this->params['breadcrumbs'][] = $this->title;
?>

<h1><?=$this->title; ?></h1>

<?=Html::a('Создать', ['create'], ['class' =>'btn btn-success']); ?>

<br><br>

<?php Pjax::begin(); ?>
<?=GridView::widget([
	'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
	'emptyText' => $this->title . '&nbsp;не добавлены!',
	'columns' => [
		['class' => 'yii\grid\SerialColumn'],
		'name',
        [
            'attribute' => 'user_id',
            'value' => function($model)
            {
                return $model->user->name;
            },
        ],
        [
            'class' => 'yii\grid\ActionColumn',
            'header' => 'Операции',
            'template' => '{view} {update} {delete}',
        ]
    ],
]); ?>
<?php Pjax::end(); ?>

views/admin/article/update.php
<?php
	$this->title = 'Редактирование';
	$this->params['breadcrumbs'] = [
		[
			'label' => 'Статьи',
			'url' => ['index']
		],
		[
			'label' => $this->title,
		]
	];
?>

    <h1><?=$this->title; ?></h1>

    <?=$this->render('form', [
        'model' => $model,
	    'tagList' => $tagList,
	    'selectList' => $selectList
    ]); ?>